version: "2"
run:
  tests: false
linters:
  enable:
    - asasalint
    - contextcheck
    - cyclop
    - dupl
    - errorlint
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - prealloc
    - revive
    - unconvert
    - unparam
    - usestdlibvars
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - rx_test
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
